[package]
name = "ipss-node-rust"
version = "0.1.0"
authors = ["Lev Stambler <levstamb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kademlia-dht = "1.2.0"
sha3 = "0.9.1"
